export enum END_POINTS {
  LOGIN = '/CreateOrLoginUserWithMail',
  GOOGLE_LOGIN = '/TokenVerifyLoginCreate',
  SIGNUP = '/CreateOrLoginUserWithMail',
  PREFERENCES = '/Ai/WeightPrefs',
  THREADS = '/Texts',
  SEARCH_THREADS = '/Search',
  UPVOTE = '/Upvote',
  AI_CONTENT = '/Ai/Summarize',
  AI_TAGS = '/Ai/GenerateTags',
  NEW_THREAD = '/AddNewText',
  USER_DATA = '/Users/Find',
  THREAD_INFO = '',
  PREFERENCES_WEIGHT = '/Prefs',
  GENERATE_QUIZ = '/Ai/GenerateQuiz',
  CHECK_QUIZ = '/Ai/CheckQuestions',
}
